AWSTemplateFormatVersion: 2010-09-09
Description: !Ref updater
# !FindInMap [updaters, !Ref updater, name]

Resources:
  laomengBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: laomengtemplatebucket

Parameters:
  updater:
    Type: String
    AllowedValues:
      - "weikangmeng"
      - "leicheng"
    Default: "weikangmeng"

Mappings:
  updaters:
    weikangmeng:
      name: "weikangmeng"
      nickname: "laomeng"
    leicheng:
      name: "leicheng"
      nickname: "son of rich man"
